- type: job
  id: CommandMaid
  name: job-name-command-maid
  description: job-description-command-maid
  playTimeTracker: JobCommandMaid
  requirements:
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 36000 # 10 Hours
  - !type:DepartmentTimeRequirement
    department: Command
    time: 12000 # 3 hours and 20 minutes
  - !type:RoleTimeRequirement
    role: JobJanitor
    time: 18000 # 5 Hours
  startingGear: CommandMaidGear
  icon: "JobIconCommandMaid"
  supervisors: job-supervisors-command
  setPreference: true
  goobcoins: 40
  salary: 100
  payrollDepartmentAccount: Command
  displayWeight: 0
  weight: 5
  access:
  - Command
  - Service
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned
        soulOwnedNotDevil: true
      - type: AdditionalLanguage
        speaks:
        - CorporateCodespeak
        understands:
        - CorporateCodespeak
  contracts:
  - DocumentContractEmploymentService

- type: startingGear
  id: CommandMaidGear
  equipment:
    id: CommandMaidPDA
    ears: ClothingHeadsetCommandMaid
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: CommandMaidChameleonOutfit
  job: CommandMaid
  equipment:
    head: ClothingHeadHatCommandMaid
    neck: ClothingNeckTieBowCommandMaid
    gloves: ClothingHandsGlovesCommandMaid
